### ISSUE TITLE
Is there a way to rating to title meta tag more than og:title meta tag?

### ISSUE THREAD

**Issue by ahadabasi** [andreskrey/readability.php#103]
Hello and thanks for your package 
Is there a way to get title not og:title?

**Comment by andreskrey** [comment]
Library prioritizes `og:title` over `title`: https://github.com/andreskrey/readability.php/blob/master/src/Readability.php#L345

There's no configuration option on how to set a priority over those keys. Happy to accept a patch if you're willing to code it :)
