### ISSUE TITLE
Using a different parser for HTML, and a few other small issues

### ISSUE THREAD

**Issue by fivefilters** [andreskrey/readability.php#104]
Hi Andres, firstly, really great work on Readability.php! We're hoping to use it to replace on older PHP port we use at FiveFilters.org.

I'm not sure if you're still maintaining this and accepting pull requests, but if you are, we've written a blog post covering some issues that we encountered. The blog post is here: https://www.fivefilters.org/2021/readability/. The changes we've made so far are here: https://github.com/fivefilters/readability.php. 

Happy to submit any of these changes as pull requests here if you'd like to integrate them into this repository.

**Comment by andreskrey** [comment]
Hi @fivefilters,

I'm more than happy to accept your changes, but it looks like you're a great candidate to maintain and continue the project. I'd like to pass you the torch, declare this repo archived and add something on the readme file to redirect users to your fork.

What do you think?

**Comment by fivefilters** [comment]
Thanks @andreskrey! And absolutely, would be more than happy to maintain and continue the project at the fork we created.

**Comment by andreskrey** [comment]
Deal! I'll update the readme and composer file this weekend :)

**Comment by fivefilters** [comment]
Great! :) I haven't set up the Travis automation yet on the forked repository, but I'll try to get all that setup this weekend.

**Comment by andreskrey** [comment]
Done, enjoy!

Thanks for keeping the project alive :)
