### ISSUE TITLE
Telegraph articles failing

### ISSUE THREAD

**Issue by NinoSkopac** [andreskrey/readability.php#29]
Repro URL: http://www.telegraph.co.uk/news/2017/11/16/zimbabwes-robert-mugabe-wife-grace-insisting-finishes-term-priest/

Problem: missing paragraphs from the article

**Comment by andreskrey** [comment]
Also happens in Readability.js (same issue you submitted there): https://github.com/mozilla/readability/issues/407.

Waiting for their fix.

**Comment by andreskrey** [comment]
Fixed with https://github.com/andreskrey/readability.php/commit/3626a9f648745892c89abb781f0dab48b2e29b09
