### ISSUE TITLE
Remove certain divs

### ISSUE THREAD

**Issue by enzonotario** [andreskrey/readability.php#43]
Hi! Firstly, thanks so much for your amazing work!

I want to remove certain divs based on css classes or ids. For example, removes all `div.container-to-remove`.

I think that my question is more a feature request.

Do you think that it is possible? At least, can you tell me where I have to see to add that feature? (well, I know that I have to see everything, but maybe you know where, specifically)

Thanks in advance!

**Comment by andreskrey** [comment]
Hi @enzonotario,

Feel free to submit a failing test case and so I can work with your example. Make sure you're specific with which divs should be removed and why.
