### ISSUE TITLE
Feature: pass custom CSS selectors to Readability

### ISSUE THREAD

**Issue by NinoSkopac** [andreskrey/readability.php#44]
Example HTML:

```html
<p class="content">Main content</p>
<div>Share the word on social media!</div>
```

Passing `p.content` CSS selector to Readability's constructor should return `Main content`

**Comment by andreskrey** [comment]
As stated in issue #36, instead of providing an extendable framewok the idea is to have an algorithm that works with every possible article. If you need to add "content" as positive class, please submit a failing test case and we will come up together with a solution that works for your case and every other case in the test suite.

**Comment by NinoSkopac** [comment]
Hey, I don't have a failing test case, I just oh, I just thought that
having this level of customization would be good. But, if it's not in the
framework then please disregard my issue

On Feb 6, 2018 5:04 PM, "Andres Rey" <notifications@github.com> wrote:

As stated in issue #36
<https://github.com/andreskrey/readability.php/issues/36>, instead of
providing an extendable framewok the idea is to have an algorithm that
works with every possible article. If you need to add "content" as positive
class, please submit a failing test case and we will come up together with
a solution that works for your case and every other case in the test suite.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/andreskrey/readability.php/issues/44#issuecomment-363372743>,
or mute the thread

**Comment by andreskrey** [comment]
I understand. I considered having an extendable platform but that would create multiple versions of the same algorithm. I think the correct path is to have one algorithm that covers all possible cases.

Thanks for your input anyway :)
