### ISSUE TITLE
Class 'Readability' not found

### ISSUE THREAD

**Issue by systemaddict** [andreskrey/readability.php#45]
If I try to install this with:

composer require andreskrey/readability.php

And run

use andreskrey\Readability\HTMLParser;
use andreskrey\Readability\Configuration;

$readability = new Readability(new Configuration());

I get:

PHP Fatal error:  Class 'Readability' not found

My composer.json looks like this:

{
    "require": {
        "andreskrey/readability.php": "^0.3.1"
    }
}

**Comment by andreskrey** [comment]
Bump your readability version to ^1.0. Readability class does not exist pre v1.

**Comment by systemaddict** [comment]
Strange. I get the same error on a new installation with php 7.

{
    "require": {
        "andreskrey/readability.php": "^1.1"
    }
}

**Comment by andreskrey** [comment]
You're also requiring the wrong dependencies. `andreskrey\Readability\HTMLParser;` does not exist anymore. Please see the [How to use it](https://github.com/andreskrey/readability.php#how-to-use-it) section of the documentation.

**Comment by andreskrey** [comment]
Wait, I'm an idiot. You've just spotted a bug in the documentation :/

I'll fix it right now. Meanwhile, use this chunk of code to initialize Readability:

```
use andreskrey\Readability\Configuration;
use andreskrey\Readability\Readability;

$html = file_get_contents('URL TO ARTICLE');

$parser = new Readability((new Configuration);
$parser->parse($html);
```

**Comment by systemaddict** [comment]
I thought it was me going crazy. I feel I'm closer now, but still getting

PHP Fatal error:  Uncaught Error: Class 'andreskrey\\Readability\\Readability' not found in ...

**Comment by andreskrey** [comment]
Are you including the composer `autoload.php` on your file? Try something like `include 'vendor/autoload.php';`

**Comment by systemaddict** [comment]
Sorry, I'm an idiot now. Works and thanks!
