### ISSUE TITLE
Extract issue

### ISSUE THREAD

**Issue by bibouu63** [andreskrey/readability.php#47]
Hi! Is there any solution to extract content from official source (Example : http://empres-i.fao.org/empres-i/2/obd?idOutbreak=229632&rss=t)

**Comment by andreskrey** [comment]
Not sure I'm following you. That page looks extremely thin content wise and the algorithm will discard results thinking it didn't extract the text correctly.

If you want to extract specific parts of that site I suggest you to use DOMDocument directly.

**Comment by bibouu63** [comment]
ok! Thank you
