### ISSUE TITLE
Aside tags

### ISSUE THREAD

**Issue by PedroAmorim** [andreskrey/readability.php#53]
Hi Andres!

I have an issue with this site:
https://www.engadget.com/2017/11/03/xbox-one-x-review/
I think we could remove all content from : 
/html/body/div[1]/div/div[2]/main/aside

By definition, it should be related to the content ( https://www.w3schools.com/tags/tag_aside.asp ), 
but by experience, it's more "look at our other articles!"

What do you think?

**Comment by andreskrey** [comment]
I'm not sure how the `aside` tag is causing issues with the parsing. In my browser shows up hidden and the only thing I can see as a parsing error is the "related articles" on the bottom of the text.

Can you post a screenshot of the issue?

**Comment by PedroAmorim** [comment]
Yes I mean remove the "related articles" on the bottom.

**Comment by andreskrey** [comment]
Makes sense! I'll open a issue on the JS version to get some feedback about this change. Will keep you posted :)

**Comment by andreskrey** [comment]
Submitted a PR to the JS version, we'll see if they accepted and then I'll port it back here.

**Comment by andreskrey** [comment]
Merged in JS version, change on this side is already in the `development` branch.

**Comment by andreskrey** [comment]
Commit hash is https://github.com/andreskrey/readability.php/commit/1f02919eded0c37dbcaf6aeb2153d21f18aad495
