### ISSUE TITLE
getContent issue!

### ISSUE THREAD

**Issue by abkh63** [andreskrey/readability.php#56]
Hi !
I have an issue with this site : https://www.the-star.co.ke/news/2018/03/13/warning-risks-of-food-security_c1728262

The function "parse()" returns only the title!

**Comment by andreskrey** [comment]
JS version is also failing to parse this. I'll add it as a failing test case.

**Comment by andreskrey** [comment]
Disregard my last comment, using the latest version I was able to parse everything correctly. Would you mind parsing it again using v1.2.0?

**Comment by andreskrey** [comment]
Just realized you changed the link. This one gets parsed correctly. Closing issue.

**Comment by abkh63** [comment]
Thanks! It works with v1.2.0  :)
