### ISSUE TITLE
Division By Zero Error Php

### ISSUE THREAD

**Issue by saajsa** [andreskrey/readability.php#64]
I am getting a error message that has resulted in my stats to encounter the error.  
<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  Division by zero</p>
<p>Filename: controllers/Api.php</p>
<p>Line Number: 93</p>

Here is the Line 93 : 
[90] $weekrate = $bht - $ohc;
.		if ( empty( $ohc ) ) {
.			$weekrate = 'N/A';
**[93]		} else $weekrate = floor( $weekrate / $ohc * 100 );**

**Comment by andreskrey** [comment]
Not sure what you're talking about. That line of code is not related to this project. Closing.
