### ISSUE TITLE
JavaScript code included in returned content

### ISSUE THREAD

**Issue by sfatfarma** [andreskrey/readability.php#66]
Hello,

Great library! Congrats.

I found a small issue. For some articles, I get a JavaScript code returned in content. Example: https://www.reuters.com/article/us-usa-trump-ivanka/ivanka-trump-closes-fashion-line-to-focus-on-helping-her-father-idUSKBN1KE2JN

Returned content:

WORLD IVANKA TRUMP CLOSES FASHION LINE TO FOCUS ON HELPING HER FATHER BREAKING NEWS July 24, 2018 0 (Reuters) – U.S. President Donald Trump’s daughter Ivanka Trump on Tuesday said she was shutting her fashion line to focus on her role as an informal White House adviser, where she is working on advancing working women. Since Trump’s surprise November 2016 election, his family has faced criticism that its portfolio of real estate and consumer goods businesses, which lean heavily on the Trump name as a marker of luxury, conflict with their roles as Washington officials. Critics of the president called the shutting of the brand a victory for a boycott of Trump-tied businesses that began late in the 2016 campaign. “After 17 months in Washington, I do not know when or if I will ever return to the business, but I do know that my focus for the foreseeable future will be the work I am doing here in Washington,” Ivanka Trump, 36, said in a statement on Tuesday. Amid criticism of potential conflicts of interest, Ivanka Trump in 2017 gave up day-to-day management of her clothing company and put its assets in a trust managed by family members. Her company said licensing contracts would not be renewed and those in place will be allowed to run their course. Mid-priced women’s clothing, shoes and accessories were sold under the label. The 18 people who work for the 11-year-old company will be laid off as it shuts down. Since Trump’s election, retailers including Nordstrom Inc , Hudson’s Bay Co and Sears Holdings Corp have dropped or sharply scaled back their assortment of Trump-branded products, though they typically attributed those decisions to poor sales rather than political messages. Read:  US vehicle tariffs considered as heart of attention as Trump meets EU's Juncker Ivanka Trump’s brand said in a statement that retailers including Bloomingdale’s, owned by Macy’s Inc , Dillard’s Inc and Amazon.com Inc , continued to carry her wares. According to the Wall Street Journal, online sales of Ivanka Trump’s brand fell nearly 55 percent in the 12 months to June, compared with the year-earlier period, citing Rakuten Intelligence, which gathers email receipts from 5.5 million U.S. consumers. Trump’s combative style on the campaign trail and as president have drawn the family’s brands into political fights, with some supporters hosting events at the luxury Trump International Hotel blocks from the White House even as opponents stage boycotts. The president has been a loud advocate for domestic manufacturing, prompting criticism that much of the Ivanka Trump line was made overseas, as is the vast majority of clothing and footwear sold in the United States. According to media reports, much of her product line has been sourced from China, which is the target of tariffs imposed by the president in a trade conflict. The most organised boycott of Trump-related businesses, “Grab Your Wallet,” called the news about Ivanka’s business a victory. “This is the biggest possible win for Grab Your Wallet,” the group’s co-founder, Shannon Coulter, a San Francisco marketing executive, said in a phone interview. (Reporting by Scott Malone in Boston, Barbara Goldberg and Diana Kruzman in New York and Nivedita Balu in Bengaluru; editing by Richard Chang and Cynthia Osterman) This story has not been edited by Firstpost staff and is generated by auto-feed. Updated Date: Jul 25, 2018 04:05 AM Read:  Secret tape may not add to legal jeopardy for Trump or Cohen Also Watch Social Media Star: Abhishek Bachchan, Varun Grover reveal how they handle selfies, trolls and broccoli Monday, July 16, 2018 It’s a Wrap: Soorma star Diljit Dosanjh and Hockey legend Sandeep Singh in conversation with Parul Sharma Monday, July 16, 2018 Watch: Dalit man in Uttar Pradesh defies decades of prejudice by taking out baraat in Thakur-dominated Nizampur village Monday, July 16, 2018 India’s water crisis: After govt apathy, Odisha farmer carves out 3-km canal from hills to tackle scarcity in village Sunday, July 15, 2018 Maurizio Sarri, named as new Chelsea manager, is owner Roman Abramovich’s latest gamble in quest for ‘perfect football’ ‘; console.log(titleHeading); $(‘.fp-first-video’).html(response+titleHeading); $(“#”+videoId).attr(“id”,liId); $(“#”+videoId+”-image”).attr(“src”,mainImage); $(“#”+videoId+”-title”).text(otherHead); $(“#”+videoId+”-date”).text(mainDate); $(“#”+videoId+”-image”).attr(“id”,liId+”-image”); $(“#”+videoId+”-title”).attr(“id”,liId+”-title”); $(“#”+videoId+”-date”).attr(“id”,liId+”-date”); $(“.fp-first-video”).attr(“id”,”alsoMain-“+videoId); $(“.fpvideo-wrap”).attr(“id”,”firstAlsoWatch_”+videoId) $(“#mainImage”).val(otherImage); $(“#mainDate”).val(otherDate); } }, error: function(xhr, ajaxOptions, thrownError) { console.log(‘Something went wrong..’); } }); });

As you can see, the end contains a javascript code.

Thank you for looking into this!

Regards.

**Comment by andreskrey** [comment]
This is [a known issue](https://github.com/andreskrey/readability.php#javascript-spilling-into-the-text-body). Please try parsing the text with the "SummonCthulhu"  option set to true.

**Comment by sfatfarma** [comment]
Thank you and sorry for not understanding the docs (because I read it). :)

Great library!
