### ISSUE TITLE
setFixRelativeURLs doesn't seem to apply to image URLs

### ISSUE THREAD

**Issue by W3Extensions** [andreskrey/readability.php#74]
Readability isn't setting relative URLs for the image source/src.

**Comment by W3Extensions** [comment]
This is the page causing the problem...

https://www.userchrome.org/what-is-userchrome-css.html

**Comment by andreskrey** [comment]
Could not reproduce. I'm sure your forgetting to declare the original URL in the Configuration object. It should look like this:

```php
$readability = new Readability((new Configuration())
    ->setFixRelativeURLs(true)
    ->setOriginalURL('https://www.userchrome.org/what-is-userchrome-css.html')
);
```
