### ISSUE TITLE
Problem extracting images

### ISSUE THREAD

**Issue by brainrepo** [andreskrey/readability.php#76]
There are problem extracting images when 

```
<meta property="og:image:width" content="373"/> 
```
or
```
<meta property="og:image:height" content="280"/>
```
are present in the document code.
when I get the main image I have the value 280 instead the filepath.

**Comment by andreskrey** [comment]
Yes, this was fixed with commit https://github.com/andreskrey/readability.php/commit/31059dd083d840a5054f726a2b6df03826fcf718 and will be released in the next version.
