### ISSUE TITLE
Strip all images from text

### ISSUE THREAD

**Issue by dg01d** [andreskrey/readability.php#78]
Is there any way that the script could be configured to strip **all** images from the parsed content?

I neither need nor want them (screen reader) and they just take up space which leads to breaking results.

**Comment by andreskrey** [comment]
You can get the DOMDocument from readability and remove all the tags you want.

For example:

```
$dom = $readability->getDOMDocument();
$list = $doc->getElementsByTagName("p");

while ($list->length > 0) {
    $p = $list->item(0);
    $p->parentNode->removeChild($p);
}
```

Or you could get the final HTML and then use [strip_tags](https://secure.php.net/manual/en/function.strip-tags.php).
