### ISSUE TITLE
iterator_to_array() error

### ISSUE THREAD

**Issue by thagoat** [andreskrey/readability.php#79]
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to iterator_to_array() must implement interface Traversable, null given in /tt-rss/vendor//andreskrey/Readability/Nodes/NodeTrait.php:324.
Arch Linux, PHP 7.3.2

Stack trace:
#0 /tt-rss/vendor/andreskrey/Readability/Nodes/NodeTrait.php(324): iterator_to_array(NULL)
#1 /tt-rss/vendor/andreskrey/Readability/Nodes/NodeTrait.php(421): andreskrey\Readability\Nodes\DOM\DOMText->getChildren(true)
#2 /tt-rss/vendor/andreskrey/Readability/Readability.php(1272): andreskrey\Readability\Nodes\DOM\DOMText->hasSingleTagInsideElement('td')
#3 /tt-rss/vendor/andreskrey/Readability/Readability.php(1166): andreskrey\Readability\Readability->prepArticle(Object(andreskrey\Readability\Nodes\DOM\DOMDocument))
#4 /tt-rss/vendor/andreskrey/Readability/Readability.php(155): andreskrey\Readability\Readability->rateNodes(Array)
#5 /tt-rss/vendor/andreskrey/Readability/Nodes/NodeTrait.php on line 324

**Comment by andreskrey** [comment]
Can you share the link or HTML that's causing this error? Thanks!

**Comment by thagoat** [comment]
It's run from a PHP script to update rss feeds from TinyTiny-RSS app, no HTML or link.

**Comment by andreskrey** [comment]
Maybe you can put a breakpoint before triggering Readability and dump the HTML content?

Without a test case there's no way I can debug this.

**Comment by thagoat** [comment]
Not quite sure how to do that, it's not my code, but here's his [Gogs repo](https://git.tt-rss.org/fox/tt-rss) if you want to play with it.

**Comment by andreskrey** [comment]
I'm afraid that without a test case or a reference HTML I'm not able to debug or fix this.

Closing issue.

Feel free to reopen it if you are able to get the offending HTML.

**Comment by thagoat** [comment]
Cheers
