### ISSUE TITLE
Getting Top Image

### ISSUE THREAD

**Issue by teamcoltra** [andreskrey/readability.php#8]
newspaper.py handles this like:

```
    def get_meta_img_url(self, article_url, doc):
        """Returns the 'top img' as specified by the website
        """
        top_meta_image, try_one, try_two, try_three, try_four = [None] * 5
        try_one = self.get_meta_content(doc, 'meta[property="og:image"]')
        if try_one is None:
            link_icon_kwargs = {'tag': 'link', 'attr': 'rel', 'value': 'icon'}
            elems = self.parser.getElementsByTag(doc, **link_icon_kwargs)
            try_two = elems[0].get('href') if elems else None

        if try_two is None:
            link_img_src_kwargs = \
                {'tag': 'link', 'attr': 'rel', 'value': 'img_src'}
            elems = self.parser.getElementsByTag(doc, **link_img_src_kwargs)
            try_three = elems[0].get('href') if elems else None

        if try_three is None:
            try_four = self.get_meta_content(doc, 'meta[name="og:image"]')

        top_meta_image = try_one or try_two or try_three or try_four

        if top_meta_image:
            return urllib.parse.urljoin(article_url, top_meta_image)
        return ''
```

This would be pretty straight forward in your PHP as well... 

If I get the time, I will update this issue and do it myself, but if you have time this would be a very useful feature.

**Comment by teamcoltra** [comment]
The first and most reliable one is most easy...

Add to line 195 on parse HTML
```
if ($item == 'og: image' || $item == 'twitter: image') {
  $metadata['image'] = $meta->getAttribute('content');
}
```

Try two would need to be added to your regex array I believe? Then you can just run:

```
if(empty($metadata['image'])) {

}
```

Try three is actually something you might want to look into... where you check for people formatting the metadata in the meta[name=""] method, which is wrong but the most common other way of doing it.

Maybe something like  this to check image tags.... 

> $topimage = $this->dom->getElementsByTagName('img');
>     if ($topimage) {
>         foreach($topimage->item as $key => $value) {
>             print "$key => $value\n";
>         }
>     }

**Comment by andreskrey** [comment]
I really like this idea! Readability.js sometimes fails to get the top image of the article so searching specifically for it is a good a idea.

I would like to focus on translating the js version to php completely and then start adding our own features and needs. I created a small PR to fix partially this (it only uses the first approach) in the meantime. I'll put this on hold.

Thanks!

**Comment by andreskrey** [comment]
Also if you want to go ahead and code a solution, feel free to do so :D

**Comment by teamcoltra** [comment]
Sweet, I am subscribed to readability.php so I will see changes and if I get to it I will update it to be more comprehensive.

**Comment by andreskrey** [comment]
Solve with [this commit](https://github.com/andreskrey/readability.php/commit/8212b56d642d0490ad8218cc9b0535fd0b8c8fc7).

Will be merged to master on next release. Thanks!
