### ISSUE TITLE
'installation' error

### ISSUE THREAD

**Issue by dnelub** [andreskrey/readability.php#82]
It gives following error after giving this command, $composer require andreskrey/readability.php

Using version ^2.0 for andreskrey/readability.php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package andreskrey/readability.php No version set (parsed as 1.0.0) is satisfiable by andreskrey/readability.php[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by andreskrey** [comment]
Seems to be a conflict with your dependencies, because the only thing we require is any version above 1.0 of psr/log.

Mind sharing your composer.json and composer.lock?

**Comment by andreskrey** [comment]
No response, closing.
