### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by davyk7** [andreskrey/readability.php#85]
Hi !

I'm trying your script but when I use the test script I got this error :

Fatal error: Class 'PHPUnit\Framework\TestCase' not found in /homepages/15/d202009493/htdocs/SERP2db/reader/test/ReadabilityTest.php on line 9

what am I doing wrong ? Is there any dependencies ?

Thanks !

**Comment by andreskrey** [comment]
Seems that you forgot to run composer install/update first. Or if you're using readability as a dependency, you'll have to access readabiilty's folder and run composer install there (PHPUnit is a dev dependency)
