### ISSUE TITLE
Trying to get property 'nodeName' of non-object

### ISSUE THREAD

**Issue by osthafen** [andreskrey/readability.php#90]
Occasionally I get the following Error:

Trying to get property 'nodeName' of non-object in:
readability.php/src/Readability.php on line 1079 

` while ($parentOfTopCandidate->nodeName !== 'body') { ...`

**Comment by andreskrey** [comment]
Do you have a sample HTML? Which version are you using?

**Comment by osthafen** [comment]
I'm using v2.1.0 - I think the error just came recently.
Unfortunately it happens in a kind of a black box so I can't provide a sample HTML.
I tr/catched the error to be still able to use the package.

**Comment by andreskrey** [comment]
If you can add some logging in that try catch to record the offending URL would be great. I'll close this issue for now but feel free to reopen it once you have more information.

**Comment by tweber68** [comment]
I have the same: 

```
`PHP Notice: Trying to get property of non-object in .../vendor/andreskrey/readability.php/src/Readability.php on line 1067`
```

On 3 hosts, 2 hosts don't have this error, but on 1 host this error always arises, above all with HTML content that contains mainly Javascript.
