### ISSUE TITLE
Readability plugin as used in tt-rss has quote escape problem on nytimes.com

### ISSUE THREAD

**Issue by lailoken** [andreskrey/readability.php#97]
This mostly works well, but in about 50% of the articles I get from nytimes.com I get this weird artifact:

[rss-error](https://home.e.co.za:5556/d/f/hd9OlUjMmslVICrmTnVl69ARTPun0Awq)

Usually the article follows it regardless, and it works for the rest of the articles. I did notice that the JavaScript snippit that is included was the same every time, so I looked where I could find it, and I found it in the original url:

`https://www.nytimes.com/2020/12/03/us/election-officials-threats-trump.html`

Since you may need a subscription to access this site, I’ve make a capture of a possible cause around the point I saw snippets like this in the html (when I search for the start of that JS):

[rss-snippit](https://home.e.co.za:5556/d/f/hd9OlTjlpcm3evWtz0sYulWPoCi5oVEd)

Regards,
Marius.

**Comment by lailoken** [comment]
Originally [reported here](https://community.tt-rss.org/t/af-readability-issue-on-nytimes-com/4085).

**Comment by andreskrey** [comment]
It's a known issue with libxml: https://github.com/andreskrey/readability.php#javascript-spilling-into-the-text-body

Try enabling the `summonCthulhu` flag. Let me know if that fixes it.

**Comment by andreskrey** [comment]
For the record, tt-rss is a terrible project in terms of dependencies, as they literally copied and pasted the readability (instead of using a sane solution, like composer). I don't know in which version they are stuck, so the `summonCthulhu` flag may or may not exist there.

**Comment by lailoken** [comment]
Haha, love the reference to :
https://blog.codinghorror.com/parsing-html-the-cthulhu-way/

Also enjoy:
https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags

But I'm a pragmatic coder and have parsed HTML with regex. But only for HTML snippets. I'll ask the project lead to give it a go.
